-- require('config.coc')
require('config.lsp')
require('config.bufferline')
require('config.treesitter')
require('config.telescope')
require('config.matchmaker')
require('config.editor')
require('config.tree')
require('config.hop')
require('config.package-info')
require('config.dap')
require('config.indent')
