# Exports
export ANDROID_HOME=~/Library/Android/sdk
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/opt/loggi/ops/ansible/bin:$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
export ZSH=~/.oh-my-zsh
export EDITOR=nvim
export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Oh My ZSH
ZSH_THEME="amuse"
plugins=(git z tmux nvm docker adb zsh_reload)
source $ZSH/oh-my-zsh.sh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'

# Aliases
alias nculoggi='ncu -u -f /@loggi/'
alias gbr='git branch | grep -v "master" | xargs git branch -D'
alias ctags="`brew --prefix`/bin/ctags"
alias fml='rm -rf node_modules && npm install'
alias nba='react-native run-android'
alias nbi='react-native run-ios'
alias nreset='watchman watch-del-all && npm run start'
alias rshake='adb shell input keyevent 82'
alias rreload='adb shell input keyevent 82 && adb shell input keyevent 19 && adb shell input keyevent 23'

function adbtext {
  adb shell input text "$1" && adb shell input keyevent ENTER;
}

function dcleanup {
  docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
  docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

function adbpic {
  adb shell screencap -p /sdcard/screen.png
  adb pull /sdcard/screen.png
  adb shell rm /sdcard/screen.png
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# begin appcenter completion
. <(appcenter --completion)
# end appcenter completion

USER=$USERNAME
[ -s "/Users/${USER}/.scm_breeze/scm_breeze.sh" ] && source "/Users/${USER}/.scm_breeze/scm_breeze.sh"
