local utils = require('utils')
local gset = vim.api.nvim_set_var
local nmap = utils.nmap

gset('airline#extensions#branch#enabled', 1)
gset('airline#extensions#branch#empty_message', '')
gset('airline#extensions#branch#displayed_head_limit', 20)
gset('airline#extensions#whitespace#enabled', 1)
gset('airline#extensions#tabline#enabled', 1)
gset('airline#extensions#tabline#show_tab_nr', 1)
gset('airline#extensions#tabline#tab_nr_type', 1)
gset('airline#extensions#tabline#show_buffers', 0)
gset('airline#extensions#tabline#buffer_idx_mode', 1)

nmap('<leader>1', '<Plug>AirlineSelectTab1')
nmap('<leader>2', '<Plug>AirlineSelectTab2')
nmap('<leader>3', '<Plug>AirlineSelectTab3')
nmap('<leader>4', '<Plug>AirlineSelectTab4')
nmap('<leader>5', '<Plug>AirlineSelectTab5')
nmap('<leader>6', '<Plug>AirlineSelectTab6')
nmap('<leader>7', '<Plug>AirlineSelectTab7')
nmap('<leader>8', '<Plug>AirlineSelectTab8')
nmap('<leader>9', '<Plug>AirlineSelectTab9')
nmap('<leader><', '<Plug>AirlineSelectPrevTab')
nmap('<leader>>', '<Plug>AirlineSelectNextTab')
